test:
  script:
    - pwd
    - git rev-parse HEAD
    - export LC_ALL=en_US.UTF-8
    - ''
    - bundle install --path ~/bundle-tmp
    - ''
    - bundle exec rake lint
    - ''
    - "# build without deploying, so that we know if a MR is horribly broken"
    - bundle exec rake build
  tags:
  except:
  - tags
