image: "ruby:2.1"

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install

stages:
  - test

lint:
  stage: test
  script:
    - bundle exec rake lint
  tags:
    - ruby
