image: ruby:2.1

before_script:
  - pwd
  - git rev-parse HEAD
  - export LC_ALL=en_US.UTF-8
  - source ./scripts/prepare_build.sh
  - bundle install --path vendor

cache:
  key: "website"
  paths:
    - vendor

lint:
  stage: test
  script:
    - bundle exec rake lint
  tags:
    - docker

build:
  stage: build
  script:
    - bundle exec rake build pdfs
  tags:
    - docker
  artifacts:
    paths:
      - public/

deploy:
  stage: deploy
  dependencies:
    - build
  before_script: []
  script:
    - rsync --delete -r public/ ~/public/
  environment: production
  tags:
    - deploy
  only:
    - gitlab-com/www-gitlab-com@master
