#!/bin/bash
set -e
repo=$(pwd)
cd /tmp
[[ -d www-gitlab-com ]] && rm -rf www-gitlab-com
git clone $repo
cd www-gitlab-com
bundle install --path ~/bundle
bundle exec rake
rsync -r --delete-after _site/ ~/public/
