#!/bin/bash -l
set -e
repo=$(pwd)
repo_name=$(basename ${repo%.git})
echo $repo_name
cd /tmp
[[ -d "$repo_name" ]] && rm -rf $repo_name
git clone $repo
cd $repo_name
bundle install --path ~/bundle
bundle exec rake generate
#rsync -r --delete-after _site/ ~/public/
